# Data source
spring:
  data:
    mongodb:
      username: sa
      password: MotDePasse
      host: localhost
      port: 27017
      database: Gestion_Avis
      authentication-database: admin

# log
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG


